easy_admin:
    site_name: 'Trooping'
    design:
        brand_color: '#2e243f'
        assets:
            favicon: '/favicons/favicon-96x96.png'
            css:
                - 'build/admin.css'
                - 'https://fonts.googleapis.com/css?family=Montserrat'
    entities:
        CoreValue:
            class: 'App\Entity\CoreValue'
            label: 'admin.core_value'
            list:
                help: 'admin.core_value.help'
                title: 'admin.core_value'
                fields:
                    - { property: 'name', label: 'admin.core_value.name' }
                    - { property: 'description', label: 'admin.core_value.description' }
                    - { property: 'color', label: 'admin.core_value.color', template: 'admin/color.html.twig' }
                    - { property: 'goals', label: 'admin.core_value.goals' }
            form:
                fields:
                    - { property: 'name', label: 'admin.core_value.name' }
                    - { property: 'description', label: 'admin.core_value.description' }
                    - { property: 'color', label: 'admin.core_value.color' }
                    - { property: 'goals', label: 'admin.core_value.goals' }
        Goal:
            class: 'App\Entity\Goal'
            label: 'admin.goal'
            list:
                help: 'admin.goal.help'
                title: 'admin.goal'
                fields:
                    - { property: 'name', label: 'admin.goal.name' }
                    - { property: 'coreValues', label: 'admin.goal.coreValues' }
            form:
                fields:
                    - { property: 'name', label: 'admin.goal.name' }
                    - { property: 'recurrence', label: 'admin.goal.recurrence', type: 'App\Form\Type\RecurrenceType' }
                    - { property: 'description', label: 'admin.goal.description' }
                    - { property: 'measurement', label: 'admin.goal.measurement', type_options: { required: false } }
                    - { property: 'attainable', label: 'admin.goal.attainable' }
                    - { property: 'ambitious', label: 'admin.goal.ambitious' }
                    - { property: 'plannedDate', label: 'admin.goal.plannedDate' }
                    - { property: 'coreValues', label: 'admin.goal.coreValues' }
        Responsibility:
            class: 'App\Entity\Responsibility'
            label: 'admin.responsibility'
            list:
                title: 'admin.responsibility'
                fields:
                    - { property: 'id', label: 'admin.responsibility.id' }
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
            form:
                fields:
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'description', label: 'admin.responsibility.description' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality', type: 'App\Form\Type\CriticalityType' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'

        User:
            class: 'App\Entity\User'
            label: 'admin.user'
            list:
                title: 'admin.user'
                fields:
                    - { property: 'picture', label: 'admin.user.picture', template: 'admin/user/picture.html.twig' }
                    - { property: 'email', label: 'admin.user.email' }
                    - { property: 'enabled', label: 'admin.user.enabled' }
            form:
                title: 'admin.new'
                fields:
                    - { property: 'firstname', type: 'email', label: 'admin.user.firstname' }
                    - { property: 'lastname', type: 'email', label: 'admin.user.lastname' }
                    - { property: 'email', type: 'email', label: 'admin.user.email' }
                    - { property: 'plainPassword', type: 'password', label: 'admin.user.plainPassword' }
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'
