easy_admin:
    site_name: 'Trooping'
    design:
        brand_color: '#2e243f'
        assets:
            favicon: '/favicons/favicon-96x96.png'
            css:
                - 'build/admin.css'
                - 'https://afeld.github.io/emoji-css/emoji.css'
                - 'https://fonts.googleapis.com/css?family=Montserrat'
        menu:
        - { label: 'admin.menu.ultimateGoals', entity: 'UltimateGoal', icon: ' em em-angel' }
        - { label: 'admin.menu.coreValue', entity: 'CoreValue', icon: ' em em-heart' }
        - { label: 'admin.menu.commitment', entity: 'Commitment', icon: ' em em-fist' }
        - { label: 'admin.menu.objective', entity: 'Objective', icon: ' em em-muscle' }
        - { label: 'admin.menu.objectiveEvaluation', entity: 'ObjectiveEvaluation', icon: ' em em-100' }
        - { label: 'admin.menu.responsibility', entity: 'Responsibility', icon: ' em em-point_up' }
        - { label: 'admin.menu.meeting', entity: 'Meeting', icon: ' em em-speech_balloon' }
        - { label: 'admin.menu.users', entity: 'User', icon: ' em em-bust_in_silhouette' }
        - { label: 'admin.menu.teams', entity: 'Team', icon: ' em em-busts_in_silhouette' }
        - { label: 'admin.menu.kukies', entity: 'Kuky', icon: ' em em-cookie' }
    entities:
        CoreValue:
            class: 'App\Entity\CoreValue'
            label: 'admin.core_value'
            list:
                help: 'admin.core_value.help'
                title: 'admin.core_value'
                fields:
                    - { property: 'name', label: 'admin.core_value.name' }
                    - { property: 'description', label: 'admin.core_value.description' }
                    - { property: 'color', label: 'admin.core_value.color', template: 'admin/color.html.twig' }
                    - { property: 'commitments', label: 'admin.core_value.commitments' }
            form:
                fields:
                    - { property: 'name', label: 'admin.core_value.name' }
                    - { property: 'description', label: 'admin.core_value.description' }
                    - { property: 'mantra', label: 'admin.core_value.mantra' }
                    - { property: 'color', label: 'admin.core_value.color' }
                    - { property: 'commitments', label: 'admin.core_value.commitments' }
        ObjectiveEvaluation:
            class: 'App\Entity\ObjectiveEvaluation'
            list:
                label: 'admin.objectiveEvaluation'
                fields:
                    - { property: 'id', label: 'admin.objectiveEvaluation.id' }
                    - { property: 'objective', label: 'admin.objectiveEvaluation.objective' }
                    - { property: 'user', label: 'admin.userEvaluation.user' }
                    - { property: 'value', label: 'admin.objectiveEvaluation.value' }
                    - { property: 'confidence', label: 'admin.objectiveEvaluation.confidence', template: 'admin/confidence.html.twig' }
            form:
                fields:
                    - { property: 'value', label: 'admin.objectiveEvaluation.value' }
                    - { property: 'confidence', label: 'admin.objectiveEvaluation.confidence', template: 'admin/confidence.html.twig' }
                    - { property: 'objective', label: 'admin.objectiveEvaluation.objective' }
                    - { property: 'user', label: 'admin.userEvaluation.user' }
        Objective:
            class: 'App\Entity\Objective'
            label: 'admin.objective'
            list:
                help: 'admin.objective.help'
                title: 'admin.objective'
                fields:
                    - { property: 'id', label: 'admin.objective.id' }
                    - { property: 'name', label: 'admin.objective.name' }
                    - { property: 'commitments', label: 'admin.objective.commitments' }
                    - { property: 'parent', label: 'admin.objective.parent' }
                    - { property: 'plannedDate', label: 'admin.objective.plannedDate' }
            form:
                fields:
                    - { property: 'name', label: 'admin.objective.name' }
                    - { property: 'recurrence', label: 'admin.objective.recurrence', type: 'App\Form\Type\RecurrenceType' }
                    - { property: 'description', label: 'admin.objective.description' }
                    - { property: 'measurement', label: 'admin.objective.measurement', type_options: { required: false } }
                    - { property: 'attainable', label: 'admin.objective.attainable' }
                    - { property: 'ambitious', label: 'admin.objective.ambitious' }
                    - { property: 'parent', label: 'admin.objective.parent' }
                    - { property: 'plannedDate', label: 'admin.objective.plannedDate' }
                    - { property: 'users', label: 'admin.objective.users' }
                    - { property: 'commitments', label: 'admin.objective.commitments' }
        Commitment:
            class: 'App\Entity\Commitment'
            label: 'admin.commitment'
            list:
                title: 'admin.commitment'
                help: 'admin.commitment.help'
                fields:
                - { property: 'id', label: 'admin.commitment.id' }
                - { property: 'name', label: 'admin.commitment.name' }
                - { property: 'coreValues', label: 'admin.commitment.coreValues' }
                - { property: 'objectives', label: 'admin.commitment.objectives' }
            form:
                fields:
                - { property: 'name', label: 'admin.commitment.name' }
                - { property: 'coreValues', label: 'admin.commitment.coreValues' }
                - { property: 'objectives', label: 'admin.commitment.objectives' }
        Responsibility:
            class: 'App\Entity\Responsibility'
            label: 'admin.responsibility'
            list:
                title: 'admin.responsibility'
                help: 'admin.responsibility.help'
                fields:
                    - { property: 'id', label: 'admin.responsibility.id' }
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality', template: 'admin/criticality.html.twig' }
                    - { property: 'leaderInvolvements', label: 'admin.responsibility.leaderInvolvements', template: 'admin/responsibility/involvementers.html.twig' }
                    - { property: 'advisorInvolvements', label: 'admin.responsibility.advisorInvolvements', template: 'admin/responsibility/involvementers.html.twig' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
            form:
                fields:
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'description', label: 'admin.responsibility.description' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality', type: 'App\Form\Type\CriticalityType' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
                    -
                      property: 'leaderInvolvements'
                      label: 'admin.responsibility.leaderInvolvements'
                      type: 'collection'
                      type_options:
                          entry_type: App\Form\LeaderInvolvementType
                          allow_delete: true
                          allow_add: true
                          by_reference: false
                    -
                      property: 'advisorInvolvements'
                      label: 'admin.responsibility.advisorInvolvements'
                      type: 'collection'
                      type_options:
                          entry_type: App\Form\AdvisorInvolvementType
                          allow_delete: true
                          allow_add: true
                          by_reference: false
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'
        User:
            class: 'App\Entity\User'
            label: 'admin.user'
            list:
                title: 'admin.user'
                fields:
                    - { property: 'picture', label: 'admin.user.picture', template: 'admin/user/picture.html.twig' }
                    - { property: 'email', label: 'admin.user.email' }
                    - { property: 'enabled', label: 'admin.user.enabled' }
            form:
                title: 'admin.new'
                fields:
                    - { property: 'firstname', label: 'admin.user.firstname' }
                    - { property: 'lastname', label: 'admin.user.lastname' }
                    - { property: 'email', type: 'email', label: 'admin.user.email' }
                    - { property: 'plainPassword', type: 'password', label: 'admin.user.plainPassword' }
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'
        Meeting:
            class: 'App\Entity\Meeting'
            list:
                title: 'admin.meeting'
        Kuky:
            class: 'App\Entity\Kuky'
        UltimateGoal:
            class: 'App\Entity\UltimateGoal'
            label: 'admin.ultimateGoal'
        Team:
            class: 'App\Entity\Team'
            list:
                title: 'admin.team'
                fields:
                    - { property: 'id', label: 'admin.team.id' }
                    - { property: 'name', label: 'admin.team.name' }
                    - { property: 'members', label: 'admin.team.members' }
                    - { property: 'parent', label: 'admin.team.parent' }
            form:
                fields:
                    - { property: 'name', label: 'admin.team.name' }
                    - { property: 'members', label: 'admin.team.members' }
                    - { property: 'parent', label: 'admin.team.parent' }
