easy_admin:
    site_name: 'Trooping'
    design:
        brand_color: '#2e243f'
        assets:
            favicon: '/favicons/favicon-96x96.png'
            css:
                - 'build/admin.css'
                - 'https://afeld.github.io/emoji-css/emoji.css'
                - 'https://fonts.googleapis.com/css?family=Montserrat'
        menu:
        - { label: 'admin.menu.goal', entity: 'Goal', icon: ' em em-muscle' }
        - { label: 'admin.menu.goalEvaluation', entity: 'GoalEvaluation', icon: ' em em-100' }
        - { label: 'admin.menu.coreValue', entity: 'CoreValue', icon: ' em em-heart' }
        - { label: 'admin.menu.responsibility', entity: 'Responsibility', icon: ' em em-point_up' }
        - { label: 'admin.menu.meeting', entity: 'Meeting', icon: ' em em-speech_balloon' }
        - { label: 'admin.menu.users', entity: 'User', icon: ' em em-bust_in_silhouette' }
        - { label: 'admin.menu.teams', entity: 'Team', icon: ' em em-busts_in_silhouette' }
        - { label: 'admin.menu.kukies', entity: 'Kuky', icon: ' em em-cookie' }
    entities:
        CoreValue:
            class: 'App\Entity\CoreValue'
            label: 'admin.core_value'
            list:
                help: 'admin.core_value.help'
                title: 'admin.core_value'
                fields:
                    - { property: 'name', label: 'admin.core_value.name' }
                    - { property: 'description', label: 'admin.core_value.description' }
                    - { property: 'color', label: 'admin.core_value.color', template: 'admin/color.html.twig' }
                    - { property: 'goals', label: 'admin.core_value.goals' }
            form:
                fields:
                    - { property: 'name', label: 'admin.core_value.name' }
                    - { property: 'description', label: 'admin.core_value.description' }
                    - { property: 'mantra', label: 'admin.core_value.mantra' }
                    - { property: 'color', label: 'admin.core_value.color' }
                    - { property: 'goals', label: 'admin.core_value.goals' }
        GoalEvaluation:
            class: 'App\Entity\GoalEvaluation'
            list:
                label: 'admin.goalEvaluation'
                fields:
                    - { property: 'id', label: 'admin.goalEvaluation.id' }
                    - { property: 'goal', label: 'admin.goalEvaluation.goal' }
                    - { property: 'user', label: 'admin.userEvaluation.user' }
                    - { property: 'value', label: 'admin.goalEvaluation.value' }
                    - { property: 'confidence', label: 'admin.goalEvaluation.confidence', template: 'admin/confidence.html.twig' }
            form:
                fields:
                    - { property: 'value', label: 'admin.goalEvaluation.value' }
                    - { property: 'confidence', label: 'admin.goalEvaluation.confidence', template: 'admin/confidence.html.twig' }
                    - { property: 'goal', label: 'admin.goalEvaluation.goal' }
                    - { property: 'user', label: 'admin.userEvaluation.user' }
        Goal:
            class: 'App\Entity\Goal'
            label: 'admin.goal'
            list:
                help: 'admin.goal.help'
                title: 'admin.goal'
                fields:
                    - { property: 'id', label: 'admin.goal.id' }
                    - { property: 'name', label: 'admin.goal.name' }
                    - { property: 'coreValues', label: 'admin.goal.coreValues' }
                    - { property: 'parent', label: 'admin.goal.parent' }
                    - { property: 'plannedDate', label: 'admin.goal.plannedDate' }
            form:
                fields:
                    - { property: 'name', label: 'admin.goal.name' }
                    - { property: 'recurrence', label: 'admin.goal.recurrence', type: 'App\Form\Type\RecurrenceType' }
                    - { property: 'description', label: 'admin.goal.description' }
                    - { property: 'measurement', label: 'admin.goal.measurement', type_options: { required: false } }
                    - { property: 'attainable', label: 'admin.goal.attainable' }
                    - { property: 'ambitious', label: 'admin.goal.ambitious' }
                    - { property: 'parent', label: 'admin.goal.parent' }
                    - { property: 'plannedDate', label: 'admin.goal.plannedDate' }
                    - { property: 'user', label: 'admin.goal.user' }
                    - { property: 'coreValues', label: 'admin.goal.coreValues' }
        Responsibility:
            class: 'App\Entity\Responsibility'
            label: 'admin.responsibility'
            list:
                title: 'admin.responsibility'
                help: 'admin.responsibility.help'
                fields:
                    - { property: 'id', label: 'admin.responsibility.id' }
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality', template: 'admin/criticality.html.twig' }
                    - { property: 'leaderInvolvements', label: 'admin.responsibility.leaderInvolvements', template: 'admin/responsibility/involvementers.html.twig' }
                    - { property: 'advisorInvolvements', label: 'admin.responsibility.advisorInvolvements', template: 'admin/responsibility/involvementers.html.twig' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
            form:
                fields:
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'description', label: 'admin.responsibility.description' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality', type: 'App\Form\Type\CriticalityType' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
                    -
                      property: 'leaderInvolvements'
                      label: 'admin.responsibility.leaderInvolvements'
                      type: 'collection'
                      type_options:
                          entry_type: App\Form\LeaderInvolvementType
                          allow_delete: true
                          allow_add: true
                          by_reference: false
                    -
                      property: 'advisorInvolvements'
                      label: 'admin.responsibility.advisorInvolvements'
                      type: 'collection'
                      type_options:
                          entry_type: App\Form\AdvisorInvolvementType
                          allow_delete: true
                          allow_add: true
                          by_reference: false
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'
        User:
            class: 'App\Entity\User'
            label: 'admin.user'
            list:
                title: 'admin.user'
                fields:
                    - { property: 'picture', label: 'admin.user.picture', template: 'admin/user/picture.html.twig' }
                    - { property: 'email', label: 'admin.user.email' }
                    - { property: 'enabled', label: 'admin.user.enabled' }
            form:
                title: 'admin.new'
                fields:
                    - { property: 'firstname', label: 'admin.user.firstname' }
                    - { property: 'lastname', label: 'admin.user.lastname' }
                    - { property: 'email', type: 'email', label: 'admin.user.email' }
                    - { property: 'plainPassword', type: 'password', label: 'admin.user.plainPassword' }
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'
        Meeting:
            class: 'App\Entity\Meeting'
            list:
                title: 'admin.meeting'
        Kuky:
            class: 'App\Entity\Kuky'
        Team:
            class: 'App\Entity\Team'
            list:
                title: 'admin.team'
                fields:
                    - { property: 'id', label: 'admin.team.id' }
                    - { property: 'name', label: 'admin.team.name' }
                    - { property: 'members', label: 'admin.team.members' }
                    - { property: 'parent', label: 'admin.team.parent' }
            form:
                fields:
                    - { property: 'name', label: 'admin.team.name' }
                    - { property: 'members', label: 'admin.team.members' }
                    - { property: 'parent', label: 'admin.team.parent' }
