easy_admin:
    entities:
        Responsibility:
            class: 'App\Entity\Responsibility'
            label: 'admin.responsibility'
            list:
                title: 'admin.responsibility'
                fields:
                    - { property: 'id', label: 'admin.responsibility.id' }
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
            form:
                fields:
                    - { property: 'name', label: 'admin.responsibility.name' }
                    - { property: 'description', label: 'admin.responsibility.description' }
                    - { property: 'criticality', label: 'admin.responsibility.criticality', type: 'App\Form\Type\CriticalityType' }
                    - { property: 'enabled', label: 'admin.responsibility.enabled' }
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'

        User:
            class: 'App\Entity\User'
            label: 'admin.user'
            list:
                title: 'admin.user'
                fields:
                    - { property: 'picture', label: 'admin.user.picture', template: 'admin/user/picture.html.twig' }
                    - { property: 'email', label: 'admin.user.email' }
                    - { property: 'enabled', label: 'admin.user.enabled' }
            form:
                title: 'admin.new'
                fields:
                    - { property: 'firstname', type: 'email', label: 'admin.user.firstname' }
                    - { property: 'lastname', type: 'email', label: 'admin.user.lastname' }
                    - { property: 'email', type: 'email', label: 'admin.user.email' }
                    - { property: 'plainPassword', type: 'password', label: 'admin.user.plainPassword' }
            edit:
                title: 'admin.edit'
            new:
                title: 'admin.new'
