jms_translation:
    configs:
        app:
            dirs: ['%kernel.project_dir%/config/packages', '%kernel.project_dir%/src', '%kernel.project_dir%/templates']
            output_dir: '%kernel.project_dir%/translations'
            excluded_names: ['*TestCase.php', '*Test.php']
