# Read the documentation: https://github.com/hautelook/AliceBundle/blob/v2.1/README.md
hautelook_alice:
    fixtures_path: 'DataFixtures'
    root_dirs:
        - '%kernel.root_dir%'
        - '%kernel.project_dir%'